// resumer/src/components/SignUpForm.vue
<template>
  <div>
    <form @submit.prevent="signUp">
      <div class="row">
        <label>用户名</label>
        <input type="text" v-model="formData.username" required>
      </div>
      <div class="row">
        <label>密码</label>
        <input type="password" v-model="formData.password" required>
      </div>
      <div class="actions">
        <input type="submit" value="提交">
        <span class="errorMessage">{{ errorMessage }}</span>
      </div>
    </form>
  </div>
</template>

<script>
import AV from '../lib/leancloud'
import getErrorMessage from '../lib/getErrorMessage'
import getAVUser from '../lib/getAVUser'

export default {
  name: 'SignUpForm',
  data () {
    return {
      formData: {
        username: '',
        password: ''
      },
      errorMessage: ''
    }
  },
  created () {},
  methods: {
    signUp () {
      let {username, password} = this.formData
      var user = new AV.User()
      user.setUsername(username)
      user.setPassword(password)
      user.signUp().then(() => {
        this.$emit('success', getAVUser())
      }, (error) => {
        this.errorMessage = getErrorMessage(error)
      })
    }
  }
}
</script>

<style lang="css">
</style>

// todo-react/src/SignUpForm.js
import React, {Component} from 'react'

export default class SignUpForm extends Component {
  render () {
    return (
      <form className="signUp" onSubmit={this.props.onSubmit.bind(this)}> {}
        <div className="row">
          <label>邮箱</label>
          <input type="text" value={this.props.formData.email}
            onChange={this.props.onChange.bind(this, 'email')}/>
        </div>
        <div className="row">
          <label>用户名</label>
          <input type="text" value={this.props.formData.username}
            onChange={this.props.onChange.bind(this, 'username')}/>
        </div>
        <div className="row">
          <label>密码</label>
          <input type="password" value={this.props.formData.password}
            onChange={this.props.onChange.bind(this, 'password')}/>
        </div>
        <div className="row actions">
          <button type="submit">注册</button>
        </div>
      </form>
    )
  }
}
